language: go
distro: trusty
services: docker

go:
    - 1.6
env:
    global:
        - secure: RHM9a6jCzO12JpRwyyJflTKFamfy3SOWBEtaX1wqij7JQ3ZNlYXZPK+DhMNluzfEOnbQ+aMcPWT5OSXVXTgeQsJg+uxyfiIhlhLEKl1CK9ct8qbdYkVCw3ttHvz6e9p1kBMTXPCpBz9Ew7ds+XZsttXxBr8peRQP6P1EuOGlNCm6OMkMzpSH6uLaqVWH8X9Y5u910jkXu2XrWOfwnT0hg6JiT+tAS7pi7roKmkPAqBg4+ROY9KFxAtZ9KvcTolpVhCuVdwmOGBvVx5NDmo6n6hPFEn7qx3dDRcuNu9sLG8YNvoINBJs90eX/HJdSneEVi9IyGTDo5xefZfdKUnga41+RLlVrSaDMZEQfs/r614Zn7E8MBcyMX7cfrh6T9MVcppKWtSTrIbbInmjeo7Sq7xYkrw0qbfXAu24y6yhuBKr4KKgmjxWvIhjIG44E4cLlO93zuOvS+X01Aq7YXFSya7Uhk2YGvotMuLuPbvspzpMEhMTgfGPC+S7B71F4TKy+ufMSdg6P4LUPyeLBd5sTG3QhLEMQlIhlmytHLJBjVG6tn8rUztrsCHVBsUqiiiHFEvaQTGeG3bLoB29qDmqcDbIyW7Ri37xRWG66jeZfxg38GnRklY1lbiotO3tyqxHLxFernXzeKqvAikxGlmeQpH+mAMvxXsKz2ej8OUiP7fk=
        - secure: "mt/M39VCvfyG9Zn9ZKxymV9W1MlwHr2twrX7JjGhgsVc9SyJaq++enUTnb3boJrqXspOzsT+VRiGPOi/QmoEhtpZGp33/uV4YqyIC85iung1BWiPXfXEKpqkJ7vlWzlAp/SHsodOChB1l1JYYK64v47Lp+KR7XjQ9KJ/XF+1kDJG1xH8GYvnlYiXhCJ0I4MXTKnda7WBNHByJB2wQDDuvQEBPEVMMcrKGL3Hmhcu1yKNkpUE+jnpp2a+0orhXhDpF49bu2eJLWGPa/gfrL6KgPBydlgE80EsWuFNFK45zDV+K04aH/3nDfDq3p5RT+8vGrj6PUVPYF7TeIY/FYcxMOVHwzLinujnAUDxn8o4aLgGlFfznkuSOFA60RCsptSMiZqwT0D7uKV+nEbOw8HaWlZLXXlozEW8Xyr5AqkaCsa01lJ59GKIBBLr/fsvY/e3mX2RaAscV2Xur/BhD3xod5N0ZR/tQyG2hZeFfC9YV3iqQCXUSTUhibXReBKDHj7W2ZrMRmzjAnfjvalWZq7GeJ+1o00OLPtbMwwrbe7Bh00Hiqh31IfQdjr/fPcBm71Y3a7qIAbdjUaf41+kiji6Zrpa5vUNfuo9uSHF/qKuCfq3Xr6lIby4Gmtn7mASpgSDR7ytHjbhxVGAG7wAFEMN0G3C+eyImL+c6PXlXb3IGm8="
        - secure: "Z/EpgKmaNOPC8lnRgu8RTizOUdSuBZWiewIS/W7BM39B4g/ZDjfbYIG5uL9rpNQBFFqnxFJPSK2AbJQGSivnMxeD183G/HlJrJBkS13j5N9rKA5ByrhgVoFlS11F6+OrbmLE4lEEn/+JniQwKZ+pGqnz3N74KvE+hwiNlK5OBdxRwAKxsuOzW3PrR0Ru6Ere1NS7I9Q6PWCy2LEvsMAOkzmQU6RlnekCTjiFeKAZNSzAVOCdLX1O9VhPHeCHfjhSsMDN3w+0eGaDPs2FhV/wpsGWrort/UvOKlTupA77BT5xqr1h0djQBodZNu+Zt8ygk6czCuUIvBEqdN2hF200o49AyPHOBwpMfpiOsbIpYrAbzXUcM4jx7HiB9iOrAbJI2jmf7pjTNTWtAZtuIE3jQEnea8r8Am+wH4qjr2ujOYPQj84flD/rx8MeqzxI4Rb2L1Bfge2XbUbTptkspJLgDxcv3Qg/ePj0k8xdQWqNjtVoE+8ToDNzPqNqSPRc0Lru0IQUP3ouAUOYsIWQT64zFzIP1Kv+bfyv9Cue5ppgSAXzQhWsBy3Zifwv6q10SettF1loNY4Y0hUdPccrDS4S5dCTseS/Ah6KaExaGaFPX9QIliW3jI8HX8wIm+9suBsXwdJLuXD9TinFdtpcF31zDisc0xlvdFaZoJbY7Cc5NBI="


install:
    - go get github.com/tools/godep

script:
    - cd "nginx-controller"
    - PREFIX="munnerz/nginx-ingress" make container

after_success:
    - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; PREFIX="munnerz/nginx-ingress" make push; fi
